[package]
name = "zkProver"
version = "0.1.0"
edition = "2021"

[dependencies]
chains-evm = { path = "../chains/evm" }
bridge = {path = "../bridge"}
clap = { version = "4.2.7", features = ["derive"] }
ethers-core = { version = "2.0.7", default-features = false }
ethers-solc = { version = "2.0.7", default-features = false }
eyre = "0.6.8"
serde = { version = "1.0.163" }
tokio = { version = "1.28.1", features = ["macros", "rt", "rt-multi-thread"] }
risc0-zkvm = "0.15.2"
zk-methods = {path = "../zk-methods", optional = true}
tempfile = "3.5.0"
bincode = "1.3.3"
hex = "0.4.3"
serde_json = "1.0.96"
clio = { version = "0.2.7", features = ["clap-parse"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["prover"]
cuda = ["risc0-zkvm/cuda"]
metal = ["risc0-zkvm/metal"]
prover = ["zk-methods"]
